// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoMXOebuJalFQK5NoAJQZpY4ZwaFQrPdY',
    appId: '1:51968627663:web:69f8cb9dc2268ad7a238ba',
    messagingSenderId: '51968627663',
    projectId: 'caseone-4076f',
    authDomain: 'caseone-4076f.firebaseapp.com',
    storageBucket: 'caseone-4076f.appspot.com',
    measurementId: 'G-HMX9G1463Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLOHsfs7CUogidgvn6fBQnK47_KyZsAHk',
    appId: '1:51968627663:android:866cbe5dd7a475b3a238ba',
    messagingSenderId: '51968627663',
    projectId: 'caseone-4076f',
    storageBucket: 'caseone-4076f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYcJemiOYLljau5bcfPfcG-a7rnxzPFZM',
    appId: '1:51968627663:ios:bece31b9601af1daa238ba',
    messagingSenderId: '51968627663',
    projectId: 'caseone-4076f',
    storageBucket: 'caseone-4076f.appspot.com',
    iosBundleId: 'com.example.caseone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYcJemiOYLljau5bcfPfcG-a7rnxzPFZM',
    appId: '1:51968627663:ios:a5ee955b63fc0cd8a238ba',
    messagingSenderId: '51968627663',
    projectId: 'caseone-4076f',
    storageBucket: 'caseone-4076f.appspot.com',
    iosBundleId: 'com.example.caseone.RunnerTests',
  );
}
